//! Canonical list of HTTP handlers mounted by the Actix app (`src/main.rs` + `src/routes/*`).
//! Used to document and assert integration coverage. Count must match `.route(` registrations:
//! 112 in `src/routes/*.rs` + `GET /api/health` in `src/main.rs` = **113** routes.

#[test]
fn registered_api_route_count_matches_actix_registrations() {
    assert_eq!(
        ROUTES.len(),
        113,
        "update ROUTES when adding/removing .route() in src/ (expect 112 in routes/*.rs + health in main.rs)",
    );
}

/// One entry per Actix registration: `(HTTP method, path pattern)`.
/// Path patterns use `{id}` / `{cid}` placeholders where the app has path params.
#[rustfmt::skip]
pub static ROUTES: &[(&str, &str)] = &[
    ("GET", "/api/health"),
    ("POST", "/api/auth/register"),
    ("POST", "/api/auth/login"),
    ("POST", "/api/auth/logout"),
    ("POST", "/api/auth/stepup"),
    ("GET", "/api/auth/session"),
    ("GET", "/api/users"),
    ("GET", "/api/users/{id}"),
    ("PUT", "/api/users/{id}/role"),
    ("GET", "/api/devices"),
    ("POST", "/api/devices/bind"),
    ("POST", "/api/devices/trust"),
    ("DELETE", "/api/devices/{id}"),
    ("GET", "/api/audit"),
    ("GET", "/api/audit/export"),
    ("GET", "/api/audit/integrity"),
    ("GET", "/api/admin/dashboard"),
    ("GET", "/api/admin/kpi/trend"),
    ("GET", "/api/admin/overview/users"),
    ("GET", "/api/admin/overview/items"),
    ("GET", "/api/admin/overview/workorders"),
    ("POST", "/api/admin/campaigns"),
    ("GET", "/api/admin/campaigns"),
    ("GET", "/api/admin/campaigns/{id}"),
    ("PUT", "/api/admin/campaigns/{id}"),
    ("POST", "/api/admin/tags"),
    ("GET", "/api/admin/tags"),
    ("DELETE", "/api/admin/tags/{id}"),
    ("PUT", "/api/admin/categories/{id}/tags"),
    ("POST", "/api/admin/reports/generate"),
    ("POST", "/api/admin/reports/configs"),
    ("GET", "/api/admin/reports/configs"),
    ("POST", "/api/bulk/import"),
    ("GET", "/api/bulk/import"),
    ("GET", "/api/bulk/import/{id}"),
    ("POST", "/api/bulk/import/{id}/execute"),
    ("POST", "/api/bulk/export"),
    ("GET", "/api/bulk/changes"),
    ("POST", "/api/bulk/changes/{id}/revert"),
    ("GET", "/api/bulk/duplicates"),
    ("PUT", "/api/bulk/duplicates/{id}/resolve"),
    ("POST", "/api/bulk/merges"),
    ("GET", "/api/bulk/merges"),
    ("GET", "/api/bulk/merges/{id}"),
    ("PUT", "/api/bulk/merges/{id}/conflicts/{cid}"),
    ("PUT", "/api/bulk/merges/{id}/review"),
    ("GET", "/api/kb/search"),
    ("POST", "/api/kb/entries"),
    ("GET", "/api/kb/entries/{id}"),
    ("PUT", "/api/kb/entries/{id}"),
    ("DELETE", "/api/kb/entries/{id}"),
    ("GET", "/api/kb/entries/{id}/versions"),
    ("GET", "/api/kb/categories"),
    ("POST", "/api/kb/categories"),
    ("POST", "/api/kb/images"),
    ("GET", "/api/kb/images/{id}"),
    ("GET", "/api/kb/search-config"),
    ("PUT", "/api/kb/search-config"),
    ("POST", "/api/disputes"),
    ("GET", "/api/disputes"),
    ("GET", "/api/disputes/{id}"),
    ("PUT", "/api/disputes/{id}/resolve"),
    ("POST", "/api/inspection/templates"),
    ("GET", "/api/inspection/templates"),
    ("GET", "/api/inspection/templates/{id}"),
    ("PUT", "/api/inspection/templates/{id}"),
    ("DELETE", "/api/inspection/templates/{id}"),
    ("PUT", "/api/inspection/templates/{id}/subtasks"),
    ("POST", "/api/inspection/schedules"),
    ("GET", "/api/inspection/schedules"),
    ("GET", "/api/inspection/tasks"),
    ("GET", "/api/inspection/tasks/{id}"),
    ("POST", "/api/inspection/tasks/{id}/start"),
    ("POST", "/api/inspection/submissions"),
    ("GET", "/api/inspection/submissions/{id}"),
    ("PUT", "/api/inspection/submissions/{id}/review"),
    ("GET", "/api/inspection/reminders"),
    ("POST", "/api/inspection/reminders/read-all"),
    ("POST", "/api/inspection/reminders/{id}/read"),
    ("POST", "/api/inspection/reminders/{id}/dismiss"),
    ("POST", "/api/inspection/generate-instances"),
    ("POST", "/api/inspection/process-overdue"),
    ("POST", "/api/reviews/scorecards"),
    ("GET", "/api/reviews/scorecards"),
    ("GET", "/api/reviews/scorecards/{id}"),
    ("PUT", "/api/reviews/scorecards/{id}/dimensions"),
    ("POST", "/api/reviews/assignments"),
    ("GET", "/api/reviews/assignments/{id}"),
    ("POST", "/api/reviews/assignments/{id}/recuse"),
    ("POST", "/api/reviews/assignments/{id}/submit"),
    ("GET", "/api/reviews/queue"),
    ("POST", "/api/reviews/coi"),
    ("GET", "/api/reviews/coi"),
    ("DELETE", "/api/reviews/coi/{id}"),
    ("GET", "/api/reviews/{id}"),
    ("POST", "/api/messaging/templates"),
    ("GET", "/api/messaging/templates"),
    ("GET", "/api/messaging/templates/{id}"),
    ("PUT", "/api/messaging/templates/{id}"),
    ("DELETE", "/api/messaging/templates/{id}"),
    ("POST", "/api/messaging/triggers"),
    ("GET", "/api/messaging/triggers"),
    ("DELETE", "/api/messaging/triggers/{id}"),
    ("POST", "/api/messaging/fire"),
    ("GET", "/api/messaging/notifications"),
    ("POST", "/api/messaging/notifications/read-all"),
    ("POST", "/api/messaging/notifications/{id}/read"),
    ("POST", "/api/messaging/notifications/{id}/dismiss"),
    ("GET", "/api/messaging/payloads"),
    ("POST", "/api/messaging/payloads/export"),
    ("POST", "/api/messaging/payloads/mark-delivered"),
    ("POST", "/api/messaging/payloads/mark-failed"),
    ("GET", "/api/messaging/payloads/{id}/log"),
];

/// `hit(...)` calls after the preamble (`GET /api/health`, `POST /api/auth/register`, `POST /api/auth/login`).
pub const API_SURFACE_HIT_COUNT: usize = ROUTES.len() - 3;

/// Total `hit(...)` calls in `every_api_route_handles_request_over_http` (must equal [`ROUTES`] length).
pub const API_INTEGRATION_HTTP_CALLS: usize = ROUTES.len();
